CONFIG_ZMK_DEFAULT_LAYER=y
CONFIG_ZMK_DEFAULT_LAYER_MIN_INDEX=0
CONFIG_ZMK_DEFAULT_LAYER_MAX_INDEX=1

CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=250
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=50
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

CONFIG_RGBLED_WIDGET_CONN_COLOR_CONNECTED=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_ADVERTISING=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_DISCONNECTED=0
CONFIG_RGBLED_WIDGET_CONN_COLOR_USB=0

CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=n
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=7
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=5
CONFIG_RGBLED_WIDGET_LAYER_7_COLOR=5
CONFIG_RGBLED_WIDGET_LAYER_8_COLOR=4
