manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: keebJP
      url-base: https://github.com/keebJP

    - name: ssbb
      url-base: https://github.com/ssbb

    - name: Hqzuki
      url-base: https://github.com/Hqzuki

    - name: cormoran
      url-base: https://github.com/cormoran

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3-branch
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: keebJP
      revision: main

    - name: zmk-mouse-gesture
      remote: Hqzuki
      revision: v1

    - name: zmk-listeners
      remote: ssbb
      revision: v1

    - name: zmk-feature-default-layer
      remote: cormoran
      revision: main

  self:
    path: config
